(load "solver-constants.scm")
(load "system.scm")
(load "functions.scm")

(display "all-nodes: ") 
(newline)
(display all-nodes)
(newline)
(display "adjacency list for directed graph: ")
(newline)
(display (adjacency-list system #t))
(newline)
(display "adjacency list for undirected graph: ")
(newline)
(display (adjacency-list system #f))
